development:
  adapter: postgresql
  encoding: unicode
  database: newApp
  pool: 5
  host: localhost
  username: postgres 
  password: '9729144954'

test:
  adapter: postgresql
  encoding: unicode
  database: newApp_test
  pool: 5
  username: postgres 
  password: '9729144954'

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
